### ISSUE TITLE
Clipp only selected part of email

### ISSUE THREAD

**Issue by ferileho** [KNHaw/ThunderbirdObsidianClipper#22] opened 2024-04-28 21:03 UTC
It would be great if only what I select by mouse in the mail could be sent to obsidian. Often the emails are full of previous communication. Right now I do this by deleting it in Obsidian after the fact. But these are often very long.. And marking the beginning of an email in Thunderbird is easier.

**Comment by KNHaw** [comment] 2024-04-29 00:50
Thank you for reaching out on this issue. I already have this on the roadmap and it will be in the next release. Others have asked for this and it is actually a duplicate of [Issue 12](https://github.com/KNHaw/ThunderbirdObsidianClipper/issues/12) but I will leave this open so you can get updates instead of having to watch that issue.

The next release is coming soon, but I keep getting sidetracked on my day job. I will let you know when it comes out, though.

Thanks again for using ObsidianClipper!

**Comment by ferileho** [comment] 2024-04-29 05:11
Thank you :)

**Comment by KNHaw** [comment] 2024-05-29 06:16
For text selection, it took a little longer than expected, but I have fixed this in V0.4.0. Just select the desired text before clipping and only that part should be clipped. Please take a peek and let me know how you like it. I will close this issue out in the next few days unless you find issue with it.

@bepolymathe - For the TODO, what exactly do you have in mind? I'm unsure what this would look like.

**Comment by ferileho** [comment] 2024-05-29 06:31
Text selection looks fine. Thank you :)

**Comment by KNHaw** [comment] 2024-06-05 13:56
Thanks! I'm going to close this as fixed. Please let me know if anything else crops up. Thanks for using ObsidianClipper!

**Closed by KNHaw** 2024-06-05 13:56 UTC
Labels: duplicate, enhancement
